# Generated by Django 6.1.1 on 2026-09-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
