# Generated by Django 6.1.1 on 2026-10-03 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.categoria'),
        ),
    ]
